[package]
name = "du-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
fxhash = "0.2.1"
itoa = "1.0.15"
nix = {version = "0.29.0", features = ["dir", "fs"]}

[profile.release]
strip = false
codegen-units = 1
lto = "fat"
opt-level = "s"
panic = "abort"

